services:
    proxy:
        build:
            context: ./images/nginx
        ports:
            - "${SERVER_PORT:-443}:8443"
        restart: always
        depends_on:
            - jupyterhub
        environment:
            SERVER_NAME: "${SERVER_NAME}"
        networks:
            - backend
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf.template:ro
            - ./cert/server.cer:/etc/nginx/ssl/server.cer:ro
            - ./cert/server.key:/etc/nginx/ssl/server.key:ro
        command: >
          /bin/bash -c
          "envsubst '$$SERVER_NAME'
          < /etc/nginx/conf.d/default.conf.template
          > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    jupyterhub:
        build:
            context: ./images/jupyterhub
        user: root
        restart: always
        environment:
            SINGLE_USER_IMAGE: "${SINGLE_USER_IMAGE:-niicloudoperation/notebook}"
            SINGLE_USER_DEFAULT_URL: "${SINGLE_USER_DEFAULT_URL:-/tree}"
            SINGLE_USER_APP: "${SINGLE_USER_APP:-jupyter_server.serverapp.ServerApp}"
            SINGLE_USER_MEM_LIMIT: "${SINGLE_USER_MEM_LIMIT:-}"
            BACKEND_NETWORK: "jupyterhub_backend"
            SERVER_SIGNATURE_HOST_PATH: "/var/lib/jupyterhub/data/server_signature"
            SHARED_DIR: "${SHARED_DIR:-/var/lib/jupyterhub/share}"
            USERS_DIR: "${USERS_DIR:-/home/user-notebooks}"
            ADMIN_GROUPS: "${ADMIN_GROUPS:-wheel}"
            DEBUG: "${DEBUG:-no}"
            CULL_SERVER: "${CULL_SERVER:-no}"
            CULL_SERVER_IDLE_TIMEOUT: "${CULL_SERVER_IDLE_TIMEOUT:-600}"
            CULL_SERVER_MAX_AGE: "${CULL_SERVER_MAX_AGE:-0}"
            CULL_SERVER_EVERY: "${CULL_SERVER_EVERY:-0}"
            LC_WRAPPER_FLUENTD_HOST: "${LC_WRAPPER_FLUENTD_HOST:-}"
            LC_WRAPPER_FLUENTD_PORT: "${LC_WRAPPER_FLUENTD_PORT:-24224}"
            SIDESTICKIES_SCRAPBOX_PROJECT_ID: "${SIDESTICKIES_SCRAPBOX_PROJECT_ID:-}"
            SIDESTICKIES_SCRAPBOX_COOKIE_CONNECT_SID: "${SIDESTICKIES_SCRAPBOX_COOKIE_CONNECT_SID:-}"
            SIDESTICKIES_EP_WEAVE_URL: "${SIDESTICKIES_EP_WEAVE_URL:-}"
            SIDESTICKIES_EP_WEAVE_API_KEY: "${SIDESTICKIES_EP_WEAVE_API_KEY:-}"
            SIDESTICKIES_EP_WEAVE_API_URL: "${SIDESTICKIES_EP_WEAVE_API_URL:-}"
            NBSEARCHDB_SOLR_BASE_URL: ${NBSEARCHDB_SOLR_BASE_URL:-http://localhost:8983}
            NBSEARCHDB_SOLR_BASIC_AUTH_USERNAME: ${NBSEARCHDB_SOLR_BASIC_AUTH_USERNAME:-}
            NBSEARCHDB_SOLR_BASIC_AUTH_PASSWORD: ${NBSEARCHDB_SOLR_BASIC_AUTH_PASSWORD:-}
            NBSEARCHDB_S3_ENDPOINT_URL: "${NBSEARCHDB_S3_ENDPOINT_URL:-http://localhost:9000}"
            NBSEARCHDB_S3_ACCESS_KEY: "${NBSEARCHDB_S3_ACCESS_KEY:-}"
            NBSEARCHDB_S3_SECRET_KEY: "${NBSEARCHDB_S3_SECRET_KEY:-}"
            NBSEARCHDB_S3_REGION_NAME: "${NBSEARCHDB_S3_REGION_NAME:-}"
            NBSEARCHDB_S3_BUCKET_NAME: "${NBSEARCHDB_S3_BUCKET_NAME:-}"
            NBSEARCHDB_SOLR_NOTEBOOK: "${NBSEARCHDB_SOLR_NOTEBOOK:-jupyter-notebook}"
            NBSEARCHDB_SOLR_CELL: "${NBSEARCHDB_SOLR_CELL:-jupyter-cell}"
            NBSEARCHDB_MY_SERVER_URL: "${NBSEARCHDB_MY_SERVER_URL:-http://localhost:8888/}"
            NBSEARCHDB_AUTO_UPDATE: "${NBSEARCHDB_AUTO_UPDATE:-}"
            NBWHISPER_SKYWAY_API_TOKEN: "${NBWHISPER_SKYWAY_API_TOKEN:-}"
            NBWHISPER_ROOM_MODE_FOR_WAITING_ROOM: "${NBWHISPER_ROOM_MODE_FOR_WAITING_ROOM:-}"
            NBWHISPER_ROOM_MODE_FOR_TALKING_ROOM: "${NBWHISPER_ROOM_MODE_FOR_TALKING_ROOM:-}"
        networks:
            - backend
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/var/run/jupyterhub:/var/run/jupyterhub'
            - '/var/lib/jupyterhub/data:/srv/jupyterhub/data/'
            - '/var/lib/jupyterhub/passwd/passwd:/etc/passwd:ro'
            - '/var/lib/jupyterhub/passwd/shadow:/etc/shadow:ro'
            - '/var/lib/jupyterhub/passwd/group:/etc/group:ro'
            - '${SHARED_DIR:-/var/lib/jupyterhub/share}:/var/jupyterhub/share/'
            - './jupyterhub-logo.png:/var/jupyterhub/logo.png:ro'
        command: >
          /bin/bash -c
          "jupyterhub upgrade-db && exec jupyterhub"

networks:
    backend:
        driver: bridge
        name: jupyterhub_backend

