volumes:
  nbsearch_solr_data_vol:
    external: false
  nbsearch_minio_data_vol:
    external: false

services:
  nbsearch-solr:
    build:
      context: ./images/nbsearch-solr
    volumes:
      - nbsearch_solr_data_vol:/var/solr/
    restart: always
    networks:
      - backend

  nbsearch-solr-base-proxy:
    build:
      context: ./images/nbsearch-solr-proxy
    depends_on:
      - nbsearch-solr
    restart: always
    networks:
      - backend

  nbsearch-solr-proxy:
    image: bitnami/oauth2-proxy:7
    depends_on:
      - jupyterhub
      - nbsearch-solr-base-proxy
    restart: always
    command:
      - --http-address=0.0.0.0:80
      - --proxy-prefix=/services/solr/oauth2
      - --upstream=http://nbsearch-solr-base-proxy:80/
      - --provider=oidc
      - --provider-display-name=JupyterHub
      - --client-id=${NBSEARCHDB_OAUTH_CLIENT_ID:-nbsearchdb_oauth_client_changeme}
      - --client-secret=${NBSEARCHDB_OAUTH_CLIENT_SECRET:-nbsearchdb_oauth_secret_changeme}
      - --cookie-secret=${NBSEARCHDB_COOKIE_SECRET:-nbsearchdb_cookiesecret_changeme}
      - --redirect-url=https://${SERVER_NAME}/services/solr/oauth2/callback
      - --oidc-issuer-url=http://jupyterhub:8000/services/oidcp/internal/
      - --email-domain=admin.jupyterhub
      - --skip-provider-button=true
    networks:
      - backend

  nbsearch-minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: "nbsearchak"
      MINIO_SECRET_KEY: "nbsearchsk"
    volumes:
      - nbsearch_minio_data_vol:/data
    command: ['server', '/data', '--compat']
    restart: always
    networks:
      - backend

  nbsearch-provisioner:
    build:
      context: ./images/nbsearch-provisioner
    volumes:
      - '/home/user-notebooks:/user-notebooks'

  nbsearch-crawler:
    build:
      context: ./images/nbsearch-crawler
    volumes:
      - '/home/user-notebooks:/home/jovyan/notebooks:ro'
    environment:
      TZ: 'JST-9'
      NBSEARCHDB_SOLR_BASE_URL: "${NBSEARCHDB_SOLR_BASE_URL:-http://nbsearch-solr:8983}"
      NBSEARCHDB_SOLR_BASIC_AUTH_USERNAME: "${NBSEARCHDB_SOLR_BASIC_AUTH_USERNAME:-}"
      NBSEARCHDB_SOLR_BASIC_AUTH_PASSWORD: "${NBSEARCHDB_SOLR_BASIC_AUTH_PASSWORD:-}"
      NBSEARCHDB_S3_ENDPOINT_URL: "${NBSEARCHDB_S3_ENDPOINT_URL:-http://nbsearch-minio:9000}"
      NBSEARCHDB_S3_ACCESS_KEY: "${NBSEARCHDB_S3_ACCESS_KEY:-nbsearchak}"
      NBSEARCHDB_S3_SECRET_KEY: "${NBSEARCHDB_S3_SECRET_KEY:-nbsearchsk}"
      NBSEARCHDB_S3_REGION_NAME: "${NBSEARCHDB_S3_REGION_NAME:-}"
      NBSEARCHDB_S3_BUCKET_NAME: "${NBSEARCHDB_S3_BUCKET_NAME:-notebooks}"
      NBSEARCHDB_SOLR_NOTEBOOK: "${NBSEARCHDB_SOLR_NOTEBOOK:-jupyter-notebook}"
      NBSEARCHDB_SOLR_CELL: "${NBSEARCHDB_SOLR_CELL:-jupyter-cell}"
      NBSEARCHDB_MY_SERVER_URL: "${NBSEARCHDB_MY_SERVER_URL:-http://localhost:8888/}"
      NBSEARCHDB_AUTO_UPDATE: "1"
    restart: always
    networks:
      - backend

  jupyterhub:
    # Override NBSEARCHDB_* environment variables
    environment:
      NBSEARCHDB_ENABLE_OIDC_SERVICE: "1"
      NBSEARCHDB_SOLR_BASE_URL: "${NBSEARCHDB_SOLR_BASE_URL:-http://nbsearch-solr:8983}"
      NBSEARCHDB_SOLR_BASIC_AUTH_USERNAME: "${NBSEARCHDB_SOLR_BASIC_AUTH_USERNAME:-}"
      NBSEARCHDB_SOLR_BASIC_AUTH_PASSWORD: "${NBSEARCHDB_SOLR_BASIC_AUTH_PASSWORD:-}"
      NBSEARCHDB_S3_ENDPOINT_URL: "${NBSEARCHDB_S3_ENDPOINT_URL:-http://nbsearch-minio:9000}"
      NBSEARCHDB_S3_ACCESS_KEY: "${NBSEARCHDB_S3_ACCESS_KEY:-nbsearchak}"
      NBSEARCHDB_S3_SECRET_KEY: "${NBSEARCHDB_S3_SECRET_KEY:-nbsearchsk}"
      NBSEARCHDB_S3_REGION_NAME: "${NBSEARCHDB_S3_REGION_NAME:-}"
      NBSEARCHDB_S3_BUCKET_NAME: "${NBSEARCHDB_S3_BUCKET_NAME:-notebooks}"
      NBSEARCHDB_SOLR_NOTEBOOK: "${NBSEARCHDB_SOLR_NOTEBOOK:-jupyter-notebook}"
      NBSEARCHDB_SOLR_CELL: "${NBSEARCHDB_SOLR_CELL:-jupyter-cell}"
      NBSEARCHDB_MY_SERVER_URL: "${NBSEARCHDB_MY_SERVER_URL:-http://localhost:8888/}"
      NBSEARCHDB_AUTO_UPDATE: ""
      NBSEARCHDB_OAUTH_CLIENT_ID: "${NBSEARCHDB_OAUTH_CLIENT_ID:-nbsearchdb_oauth_client_changeme}"
      NBSEARCHDB_OAUTH_CLIENT_SECRET: "${NBSEARCHDB_OAUTH_CLIENT_SECRET:-nbsearchdb_oauth_secret_changeme}"
    volumes:
      - './config/oidc/jupyterhub_config.py:/jupyterhub_config.d/oidc.py:ro'
      - './config/nbsearch/jupyterhub_config.py:/jupyterhub_config.d/solr.py:ro'
